Property_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import ( 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('properties/', include('properties.urls', namespace='properties')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (LeadListView, LeadDetailView, LeadCreateView, 
    LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    LeadDashboardView, CustomLoginView, MaintenanceRequestCreateView,
    MaintenanceRequestListView, MaintenanceRequestUpdateView,
    category_qr_code_detail, lead_category_qr_code, MaintenanceRequestDisplayView,
)

app_name = "leads"
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),
    path('dashboard/', LeadDashboardView.as_view(), name='lead-dashboard'),
    path('maintenance-request/create/', MaintenanceRequestCreateView.as_view(), name='maintenance-request-create'),
    path('maintenance_request/list/', MaintenanceRequestListView.as_view(), name='maintenance_request_list'),
    path('maintenance_request/update/<int:pk>/', MaintenanceRequestUpdateView.as_view(), name='maintenance_request_update'),
    path('maintenance_request/display/', MaintenanceRequestDisplayView.as_view(), name='maintenance_request_display'),
    path('category_qr_code_detail/<int:pk>/', category_qr_code_detail, name='category_qr_code_detail'),
    path('lead/<int:lead_id>/qr-code/', lead_category_qr_code, name='lead-category-qr-code'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete  
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.dispatch import receiver
from django.apps import apps

#User class extends the AbstractUser model and includes additional role fields
class User(AbstractUser):
    is_organisor = models.BooleanField(default=True) #Organisor role
    is_agent = models.BooleanField(default=False) #Agent role
    is_lead = models.BooleanField(default=False) #Lead role

#UserProfile class with one-to-one relationship to User
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

#Lead class with various fields and relationships to other models
class Lead(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    
    def __str__(self):
        if self.user is None:
            return f"Lead with ID {self.id} (No User)"
        return f"{self.user.first_name} {self.user.last_name}"

#Pre-delete signal for Lead class
@receiver(pre_delete, sender=Lead)
def pre_lead_delete(sender, instance, **kwargs):
    Apartment = apps.get_model('properties', 'Apartment')
    try:
        apartment = instance.apartment
        apartment.lead = None
        apartment.is_occupied = False
        apartment.save()
    except Apartment.DoesNotExist:
        pass
    
#Agent class with one-to-one relationship to User and foreign key to UserProfile
class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

#Category class with foreign key to UserProfile
class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

#Signal to create a UserProfile upon User creation
def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

#MaintenanceRequest class with various fields and relationships to other models
class MaintenanceRequest(models.Model):
    PENDING = "Pending"
    IN_PROGRESS = "In Progress"
    RESOLVED = "Resolved"

    STATUS_CHOICES = [
        (PENDING, "Pending"),
        (IN_PROGRESS, "In Progress"),
        (RESOLVED, "Resolved"),
    ]

    lead = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='maintenance_requests')
    apartment = models.ForeignKey("properties.Apartment", on_delete=models.CASCADE)
    description = models.TextField()
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=PENDING,
    )

    def __str__(self):
        return f"{self.lead} - {self.apartment} - {self.status}"

    @property
    def apartment_model(self):
        Apartment = apps.get_model('properties', 'Apartment')
        return Apartment.objects.get(pk=self.apartment_id)

leads/views.py
from django.shortcuts import render, reverse, get_object_or_404
from agents.mixins import OrganisorAndLoginRequiredMixin
from .mixins import LeadRequiredMixin
from django.views import generic
from django.db.models import Count
from .models import Lead, Category, MaintenanceRequest
from properties.models import Apartment
from .forms import ( LeadModelForm, CustomUserCreationForm, 
    AssignAgentForm, LeadCategoryUpdateForm, CategoryModelForm, 
    MaintenanceRequestForm, MaintenanceRequestUpdateForm
)
from django.db.models import Q
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from .utils.qr_code_generator import generate_qr_code
from django.http import FileResponse


class CustomLoginView(LoginView):
    def get_success_url(self):
        user = self.request.user
        if user.is_authenticated:
            if user.is_lead:
                return reverse("leads:lead-dashboard")
            else:
                return reverse("leads:lead-list")

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    
    def get_success_url(self):
        return reverse("leads:login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"
    
    
class LeadListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "leads/leads.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile).exclude(Q(agent__isnull=True) | Q(apartment__isnull=True))


    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            all_leads = Lead.objects.filter(organisation=user.userprofile)
            leads_with_apartments = Apartment.objects.filter(lead__in=all_leads).values_list('lead', flat=True)
            queryset = all_leads.filter(Q(agent__isnull=True) | Q(apartment__isnull=True))
            context.update({
                "unassigned_leads": queryset
            })
        return context

class LeadDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset
    
class LeadCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        return super(LeadCreateView, self).form_valid(form)



class LeadUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)
    
    def get_success_url(self):
        referer_url = self.request.headers.get('Referer')
        pk = referer_url.split("/")[-3]
        return reverse("leads:lead-detail", kwargs={"pk":pk})
    
class LeadDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead-list')
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

        
class AssignAgentView(OrganisorAndLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        apartment = form.cleaned_data["apartment"]
        lead = get_object_or_404(Lead, id=self.kwargs["pk"])
        apartment.lead = lead
        apartment.is_occupied = True
        apartment.save()
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lead = get_object_or_404(Lead, id=self.kwargs["pk"])
        context['lead'] = lead
        return context
        
class CategoryListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'leads/category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(num_leads=Count('leads'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            leads = Lead.objects.filter(
                organisation=user.userprofile
            )
        else:
            leads = Lead.objects.filter(
                organisation=user.agent.organisation
            )
        unassigned_lead_count = leads.filter(category__isnull=True).count()

        categories = context['categories']
        category_lead_counts = leads.filter(category__in=categories).values('category').annotate(count=Count('category'))

        context['unassigned_lead_count'] = unassigned_lead_count
        context['category_lead_counts'] = []

        for category in categories:
            count = 0
            for category_lead_count in category_lead_counts:
                if category == category_lead_count['category']:
                    count = category_lead_count['count']
                    break
            context['category_lead_counts'].append(count)

        return context

            
class CategoryDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"     
    context_object_name = "category"
        
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset
    
class LeadCategoryUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs={"pk": self.get_object().id})

class CategoryCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/category_create.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse('leads:category-list')
    
    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)

class CategoryUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/category_update.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("leads:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/category_delete.html"

    def get_success_url(self):
        return reverse("leads:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset
        
class LeadDashboardView(LeadRequiredMixin, generic.TemplateView):
    template_name = "leads/tenant_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lead = self.request.user.lead
        context['category'] = lead.category
        try:
            context['apartment'] = lead.apartment
        except Apartment.DoesNotExist:
            context['apartment'] = None
        return context
    

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
</div>
<div class="max-w-lg mx-auto">
    <h1  class="text-3xl text-gray-800 mb-4">Assign an agent to {{ lead.first_name }} {{ lead.last_name }}</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}
<div class="flex hover:text-blue-500">
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
    <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
</div>

<section class="text-gray-700 body-font -mt-20">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-4xl text-gray-800 mb-6">Categories</h1>
          </div>
          <div>
              <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category-create' %}">
                  Create a category
              </a>
          </div>
         </div>

      <div class="flex flex-col w-full">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                      <tr>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Name
                          </th>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Lead Count
                          </th>
                          <th scope="col" class="relative px-6 py-3">
                          <span class="sr-only">View</span>
                          </th>
                      </tr>
                  </thead>
                  <tbody>
                    <tr class="bg-white">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"> <a class="text-blue-500 hover:text-blue-800" href="#">Unassigned</a></td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ unassigned_lead_count }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <a href="#" class="text-indigo-600 hover:text-indigo-900">
                            View
                        </a>
                    </td>
                    </tr>
                    {% for category in categories %}
                    <tr class="bg-white">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ category.num_leads|default:0 }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <a href="#" class="text-indigo-600 hover:text-indigo-900">
                              View
                          </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
              </div>
          </div>
          </div>
      </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/category_qr_code_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Category: {{ category }}</h1>
{% endblock %}

leads/templates/leads/lead_dashboard.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to your dashboard, {{ request.user.username }}!</h1>
<p>Here, you can access the services offered to you.</p>
{% endblock %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<div class="flex hover:text-blue-500">
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
    <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
</div>
<section class="text-gray-700 body-font -mt-20">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead Details</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.user.first_name }} {{ lead.user.last_name }}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
            <a href="#" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Apartment</a>
          </div>
          <p class="leading-relaxed mb-4">{{ lead.description }}</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Cell phone</span>
            <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ lead.user.email }}</span>
          </div>
          <div class="flex">
            <a href="{% url 'leads:lead-update' lead.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Edit</a>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"><a href="{% url 'leads:lead-delete' lead.pk %}">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M5 8a1 1 0 011-1h12a1 1 0 011 1v10a1 1 0 01-1 1H6a1 1 0 01-1-1V8z" />
                <path d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2H3V4zm2 4v8a2 2 0 002 2h10a2 2 0 002-2V8H5zm4 1a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1zm6 0a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1z" />
              </svg></a>
            </button>
          </div>
        </div>
        <img src="{% url 'leads:lead-category-qr-code' lead.id %}" alt="QR Code for Lead Category">
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/maintenance_request_display.html
{% extends "base.html" %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{{ request.META.HTTP_REFERER }}">Go back</a>
</div>
<section class="text-gray-700 body-font -mt-20">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-4xl text-gray-800 mb-4">Maintenance Requests</h1>
          </div>
      </div>
      <div class="flex flex-col w-full">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                      <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Lead
                          </th>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Apartment
                          </th>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Description
                          </th>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Status
                          </th>
                          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Actions
                          </th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for maintenance_request in maintenance_requests %}
                            <tr class="bg-white">
                              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                {{ maintenance_request.lead }}
                              </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                  {{ maintenance_request.apartment }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                  {{ maintenance_request.description }}
                                </td> 
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                  {{ maintenance_request.get_status_display }}
                                </td>                                    
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:maintenance_request_update' maintenance_request.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                      Update
                                    </a>
                                </td>
                            </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">No maintenance requests found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}