Property_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import ( 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('properties/', include('properties.urls', namespace='properties')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

leads/urls.py
from django.urls import path
from .views import (LeadListView, LeadDetailView, LeadCreateView, 
    LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    LeadDashboardView, CustomLoginView, MaintenanceRequestCreateView,
    MaintenanceRequestListView, MaintenanceRequestUpdateView,
    category_qr_code_detail, lead_category_qr_code, MaintenanceRequestDisplayView,
)

app_name = "leads"
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),
    path('dashboard/', LeadDashboardView.as_view(), name='lead-dashboard'),
    path('maintenance-request/create/', MaintenanceRequestCreateView.as_view(), name='maintenance-request-create'),
    path('maintenance_request/list/', MaintenanceRequestListView.as_view(), name='maintenance_request_list'),
    path('maintenance_request/update/<int:pk>/', MaintenanceRequestUpdateView.as_view(), name='maintenance_request_update'),
    path('maintenance_request/display/', MaintenanceRequestDisplayView.as_view(), name='maintenance_request_display'),
    path('category_qr_code_detail/<int:pk>/', category_qr_code_detail, name='category_qr_code_detail'),
    path('lead/<int:lead_id>/qr-code/', lead_category_qr_code, name='lead-category-qr-code'),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
import random
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin

class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        send_mail(
            subject="Agent registration on Rentify",
            message="You were added as an agent on Rentify. You may now manage your tenants on the platform.",
            from_email="admin@gmail.com",
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)
    
class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        return Agent.objects.all()
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        pk = self.kwargs.get('pk')
        agent = Agent.objects.get(pk=pk)
        kwargs.update({
            'instance': agent.user,
        })
        return kwargs

class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        agent = Agent.objects.get(pk=pk)
        context['agent'] = agent
        print(agent.user.first_name)
        return context

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>
<div class="max-w-lg mx-auto">
    <h1 class="text-3xl text-gray-800 mb-4">Create a new agent</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
        <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round"
            stroke-linejoin="round" />
    </svg>
    <a href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>
<div class="max-w-lg mx-auto mt-6">
    <h1 class="text-3xl text-gray-800 mb-4">Delete {{ agent.user.first_name }} {{agent.user.last_name}}'s profile </h1>
    <p1> Are you sure you want to delete {{ agent.user.first_name }} {{agent.user.last_name}}'s profile? </p1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="w-full flex justify-between mt-6">
            <button class="w-full text-white bg-gray-300 hover:bg-gray-600 px-3 py-2 rounded-md mr-2"><a href="{% url 'agents:agent-list' %}">No, cancel</a></button>
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Yes, delete</button>
        </div>
        
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}
<div class="flex">
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
    <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  <a href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Agent</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">blabla</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Cell phone</span>
            <span class="ml-auto text-gray-900">Medium</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">4</span>
          </div>
          <div class="flex">
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Edit</a>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"><a href="{% url 'agents:agent-delete' agent.pk %}">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M5 8a1 1 0 011-1h12a1 1 0 011 1v10a1 1 0 01-1 1H6a1 1 0 01-1-1V8z" />
                <path d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2H3V4zm2 4v8a2 2 0 002 2h10a2 2 0 002-2V8H5zm4 1a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1zm6 0a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1z" />
              </svg></a>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Agents</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new agent</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agent in object_list %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ agent.user.first_name }} {{ agent.user.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ agent.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'agents:agent-update' agent.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p>There are currently no agents</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex hover:text-blue-500">
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
    <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  <a href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Agent</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          </div>

          <form method="post" action=".">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="flex">
                <button type="submit"
                    class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Save</button>
                <button
                    class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"><a
                        href="{% url 'agents:agent-delete' agent.pk %}">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
                            viewBox="0 0 24 24">
                            <path d="M5 8a1 1 0 011-1h12a1 1 0 011 1v10a1 1 0 01-1 1H6a1 1 0 01-1-1V8z" />
                            <path
                                d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2H3V4zm2 4v8a2 2 0 002 2h10a2 2 0 002-2V8H5zm4 1a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1zm6 0a1 1 0 011 1v4a1 1 0 11-2 0V9a1 1 0 011-1z" />
                        </svg></a>
                </button>
            </div>
        </form>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>






{% endblock content %}