Property_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import ( 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('properties/', include('properties.urls', namespace='properties')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (LeadListView, LeadDetailView, LeadCreateView, 
    LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    LeadDashboardView, CustomLoginView, MaintenanceRequestCreateView,
    MaintenanceRequestListView, MaintenanceRequestUpdateView,
    category_qr_code_detail, lead_category_qr_code, MaintenanceRequestDisplayView,
)

app_name = "leads"
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),
    path('dashboard/', LeadDashboardView.as_view(), name='lead-dashboard'),
    path('maintenance-request/create/', MaintenanceRequestCreateView.as_view(), name='maintenance-request-create'),
    path('maintenance_request/list/', MaintenanceRequestListView.as_view(), name='maintenance_request_list'),
    path('maintenance_request/update/<int:pk>/', MaintenanceRequestUpdateView.as_view(), name='maintenance_request_update'),
    path('maintenance_request/display/', MaintenanceRequestDisplayView.as_view(), name='maintenance_request_display'),
    path('category_qr_code_detail/<int:pk>/', category_qr_code_detail, name='category_qr_code_detail'),
    path('lead/<int:lead_id>/qr-code/', lead_category_qr_code, name='lead-category-qr-code'),
]

properties/urls.py
from django.urls import path
from .views import (
    PropertyListView, PropertyCreateView, ApartmentCreateView, 
    PropertyDetailView, UtilityCreateView, UtilityUpdateView, UtilityListView,
    UtilityDetailView, BillCreateView, BillDetailView, ApartmentDetailView,
    ApartmentUpdateView,
)

app_name = "properties"

urlpatterns = [
    path('', PropertyListView.as_view(), name='property-list'),
    path('create/', PropertyCreateView.as_view(), name='property-create'),
    path('<int:pk>/', PropertyDetailView.as_view(), name='property-detail'),
    path('create-apartment/', ApartmentCreateView.as_view(), name='apartment-create'),
    path('utilities/detail/<int:property_id>/<int:utility_pk>/', UtilityDetailView.as_view(), name='utility_detail_list'),
    path('utility/list/<int:property_id>/', UtilityListView.as_view(), name='utility-list'),
    path('utilities/create/', UtilityCreateView.as_view(), name='utility_create'),
    path('utilities/<int:pk>/update/', UtilityUpdateView.as_view(), name='utility_update'),
    path('utilities/<int:utility_id>/bills/create/', BillCreateView.as_view(), name='bill_create'),
    path('bills/<int:pk>/', BillDetailView.as_view(), name='bill_detail'),
    path('apartment/<int:pk>/', ApartmentDetailView.as_view(), name='apartment-detail'),
    path('apartment/<int:pk>/update/', ApartmentUpdateView.as_view(), name='apartment-update'),

]

properties/models.py
from django.db import models
from leads.models import UserProfile, Agent
import datetime

class Property(models.Model):
    name = models.CharField(max_length=100)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    location = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='properties/', default='default_property.jpg')

    def __str__(self):
        return self.name

class Apartment(models.Model):
    property = models.ForeignKey(Property, related_name='apartments', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    is_occupied = models.BooleanField(default=False)
    lead = models.OneToOneField('leads.Lead', null=True, blank=True, on_delete=models.SET_NULL)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField()
    rent = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='apartments/', default='default_apartment.jpg')
        
    def __str__(self):
        return f"{self.property.name} - {self.name}"

class Utility(models.Model):
    property = models.ForeignKey(Property, related_name='utilities', on_delete=models.CASCADE)
    apartment = models.ForeignKey(Apartment, related_name='utilities', null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class Bill(models.Model):
    utility = models.ForeignKey(Utility, related_name='bills', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    image = models.ImageField(upload_to='bills/', default='default_bill.jpg')
    date = models.DateField(default=datetime.date(2020, 11, 1))

    def __str__(self):
        return f"{self.utility.name} - {self.date}"

properties/forms.py
from django import forms
from .models import Property, Apartment
from .models import Utility, Bill

class PropertyModelForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = (
            'name',
            'organisation',
            'location',
            'description',
            'image', 
        )

class ApartmentModelForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = (
            'property',
            'name',
            'is_occupied',
            'lead',
            'agent',
            'description',
            'rent',
            'image', 
        )

class UtilityCreateForm(forms.ModelForm):
    class Meta:
        model = Utility
        fields = ('property', 'apartment', 'name', 'description')
        widgets = {
            'property': forms.Select(attrs={'class': 'form-control'}),
            'apartment': forms.Select(attrs={'class': 'form-control'}),
        }

class UtilityUpdateForm(forms.ModelForm):
    class Meta:
        model = Utility
        fields = ('name', 'description')

class BillModelForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['image']

properties/views.py
from django.shortcuts import render, reverse,get_object_or_404
from django.views import generic
from .models import Property, Utility, Apartment, Bill
from .forms import PropertyModelForm, ApartmentModelForm, UtilityCreateForm, UtilityUpdateForm, BillModelForm
from agents.mixins import OrganisorAndLoginRequiredMixin
import os
import tempfile
from PIL import Image
from .receipt_scanner import extract_information, preprocess_image, extract_text, extract_information

class BillCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "properties/bill_create.html"
    form_class = BillModelForm

    def process_uploaded_image(self, image):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as temp_image:
            img = Image.open(image)
            img.save(temp_image, format='JPEG')
            temp_image.flush()
            temp_image.close()
            preprocessed_image = preprocess_image(temp_image.name)
            text = extract_text(preprocessed_image)
            extracted_data = extract_information(text)
            os.unlink(temp_image.name)
        return extracted_data

    def form_valid(self, form):
        utility = Utility.objects.get(pk=self.kwargs['utility_id'])
        form.instance.utility = utility

        image = self.request.FILES.get('image')
        if image:
            extracted_data = self.process_uploaded_image(image)
            form.instance.date = extracted_data['date'] if extracted_data['date'] else form.instance.date
            form.instance.amount = extracted_data['amount']

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('properties:bill_detail', kwargs={'pk': self.object.pk})

    
class BillDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    model = Bill
    template_name = 'properties/bill_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bill = self.get_object()

        context['date'] = bill.date
        context['amount'] = bill.amount

        return context


class PropertyListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "properties/property_list.html"
    context_object_name = "properties"

    def get_queryset(self):
        return Property.objects.filter(organisation=self.request.user.userprofile)

class PropertyCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "properties/property_create.html"
    form_class = PropertyModelForm

    def get_success_url(self):
        return reverse('properties:property-list')

    def form_valid(self, form):
        property = form.save(commit=False)
        property.organisation = self.request.user.userprofile
        property.save()
        return super(PropertyCreateView, self).form_valid(form)

class PropertyDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "properties/property_detail.html"  # Fix the typo here
    context_object_name = "property"
    
    def get_queryset(self):
        return Property.objects.filter(organisation=self.request.user.userprofile)


class ApartmentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "properties/apartment_create.html"
    form_class = ApartmentModelForm

    def get_success_url(self):
        return reverse('properties:property-list')

    def form_valid(self, form):
        apartment = form.save(commit=False)
        apartment.save()
        return super(ApartmentCreateView, self).form_valid(form)

class UtilityCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    model = Utility
    form_class = UtilityCreateForm
    template_name = 'properties/utility_create.html'
        
    def get_success_url(self):
        return reverse('properties:utility-list', kwargs={'property_id': self.object.property.id})


class UtilityUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    model = Utility
    form_class = UtilityUpdateForm
    template_name = 'properties/utility_update.html'

    def get_success_url(self):
        return reverse('properties:utility_list', kwargs={'property_id': self.object.property.id})

class UtilityListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    model = Utility
    template_name = 'properties/utility_list.html'
    context_object_name = 'utilities'

    def get_queryset(self):
        property_id = self.kwargs['property_id']
        return Utility.objects.filter(property_id=property_id)
    
class UtilityDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    model = Utility
    template_name = 'properties/utility_detail_list.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Utility, property_id=self.kwargs['property_id'], pk=self.kwargs['utility_pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bills'] = Bill.objects.filter(utility=self.object)
        return context

class ApartmentDetailView(generic.DetailView):
    model = Apartment
    template_name = "properties/apartment_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ApartmentModelForm(instance=self.object)
        return context
    
class ApartmentUpdateView(generic.UpdateView):
    model = Apartment
    form_class = ApartmentModelForm
    template_name = 'properties/apartment_update.html'

    def get_success_url(self):
        return reverse('properties:apartment-detail', kwargs={'pk': self.object.property.pk})

properties/templates/properties/apartment_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

    <div class="flex hover:text-blue-500">
        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
        <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <a href="{% url 'properties:property-list' %}">Go back to Properties</a>
    </div>
    <div class="max-w-lg mx-auto">
        <h2 class="text-2xl font-semibold mb-4">Create Apartment</h2>
        <form method="POST" enctype="multipart/form-data">  
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded shadow hover:bg-blue-600">Create Apartment</button>
        </form>
    </div>


{% endblock %}

properties/templates/properties/apartment_detail.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/1F1WgPSJFldb9tILRB2P2d07gyrvv02Yg/092p" crossorigin="anonymous">
<style>
  .fade-left {
    position: relative;
  }
  .fade-left::after {
    content: "";
    display: block;
    position: absolute;
    top: 0;
    width: 160px;
    height: 100%;
    background-image: linear-gradient(to left, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1) 100%);
  }
</style>
<div class="flex hover:text-blue-500">
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
    <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  <a href="{{ request.META.HTTP_REFERER }}">Go back</a>
</div>
<div class="bg-gray-100 min-h-screen">
  <div class="container mx-auto py-12">
    <div class="flex justify-between items-start mb-8">
      <h2 class="text-4xl font-bold text-gray-600">{{ object.name }}</h2>
      <div>
        <a href="{% url 'properties:utility-list' property_id=apartment.property.pk %}" class="bg-blue-500 text-white px-4 py-2 rounded shadow hover:bg-blue-600 mr-2">View Utilities</a>
        <a href="{% url 'properties:apartment-update' pk=apartment.pk %}" class="bg-green-500 text-white px-4 py-2 rounded shadow hover:bg-green-600">Edit Apartment</a>
      </div>
    </div>
    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
      <div class="flex">
        <div class="w-1/2 p-8">
          <p class="text-gray-600 text-xl mb-4 font-semibold">Property Details</p>
          <div class="grid grid-cols-2 gap-6 mt-20">
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-building mr-2"></i>Property:</span> {{ object.property }}</p>
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-user-check mr-2"></i>Is Occupied:</span> {{ object.is_occupied }}</p>
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-user-tie mr-2"></i>Lead:</span> {{ object.lead }}</p>
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-users mr-2"></i>Agent:</span> {{ object.agent }}</p>
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-info-circle mr-2"></i>Description:</span> {{ object.description }}</p>
            <p class="mb-2"><span class="font-semibold"><i class="fas fa-dollar-sign mr-2"></i>Rent:</span> {{ object.rent }}</p>
          </div>
        </div>
        <div class="w-1/2 relative">
          <div class="fade-left">
            <img src="{{ object.image.url }}" alt="{{ object.name }} image" class="w-full h-full object-cover">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

properties/templates/properties/property_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{{ request.META.HTTP_REFERER }}">Go back</a>
  </div>
    <h2 class="text-2xl font-semibold mb-4">{{ property.name }}</h2>
    <p>{{ property.description }}</p>
    <h3 class="text-xl font-semibold mt-6 mb-4">Apartments</h3>
    <a href="{% url 'properties:apartment-create' %}" class="bg-blue-500 text-white px-4 py-2 rounded shadow hover:bg-blue-600">Add Apartments</a>
    <div class="grid grid-cols-3 gap-4 mt-6">
        {% for apartment in property.apartments.all %}
            <div class="border border-gray-200 p-4 rounded shadow">
                <a href="{% url 'properties:apartment-detail' pk=apartment.pk %}"><img class="w-full h-40 object-cover rounded" src="{{ apartment.image.url }}" alt="{{ apartment.name }}"></a>                <h4 class="text-lg font-semibold">{{ apartment.name }}</h4>
                <p>{{ apartment.description }}</p>
                <p>Rent: Rs {{ apartment.rent }}</p>
            </div>
        {% empty %}
            <p>No apartments found.</p>
        {% endfor %}
    </div>
{% endblock %}

properties/templates/properties/property_list.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-2xl font-semibold mb-4">Properties</h2>
    <a href="{% url 'properties:property-create' %}" class="bg-blue-500 text-white px-4 py-2 rounded shadow hover:bg-blue-600">Add Property</a>
    <div class="grid grid-cols-3 gap-4 mt-4">
        {% for property in properties %}
            <div class="border border-gray-200 p-4 rounded shadow">
                <a href="{% url 'properties:property-detail' property.id %}">
                    <img class="w-full h-40 object-cover rounded" src="{{ property.image.url }}" alt="{{ property.name }}">
                    <h3 class="text-xl font-semibold">{{ property.name }}</h3>
                </a>
                <p>{{ property.location }}</p>
                <p>{{ property.apartments.count }} Apartments</p>
            </div>
        {% empty %}
            <p>No properties found.</p>
        {% endfor %}
    </div>
{% endblock %}

properties/templates/properties/utility_detail_list.html
{% extends "base.html" %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{{ request.META.HTTP_REFERER }}">Go back</a>
</div>
<section class="text-gray-700 body-font -mt-20">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800 mb-4">{{ object.name }} Bills</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'properties:bill_create' utility_id=object.pk %}">
                    Add Bill
                </a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Date
                            </th>
                        </tr>
                        <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </thead>
                    <tbody>
                        {% for bill in bills %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a class="text-blue-500 hover:text-blue-800" href="{% url 'properties:bill_detail' bill.pk %}">{{ bill.date }}</a>
                                    </td>                                  
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'properties:bill_detail' bill.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            View
                                        </a>
                                    </td>
                                </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No bills for this utility.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

properties/templates/properties/utility_list.html
{% extends "base.html" %}

{% block content %}
<div class="flex hover:text-blue-500">
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6">
      <path d="M15 19L7 12L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <a href="{{ request.META.HTTP_REFERER }}">Go back</a>
  </div>
<section class="text-gray-700 body-font -mt-20">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800 mb-4">Utility List</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'properties:utility_create' %}">
                    Create Utility
                </a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Details
                            </th>                          
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for utility in utilities %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a class="text-blue-500 hover:text-blue-800" href="{% url 'properties:utility_detail_list' property_id=utility.property.pk utility_pk=utility.pk %}">{{ utility.name }}</a>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        <a href="{% url 'properties:utility_detail_list' property_id=utility.property.pk utility_pk=utility.pk %}" class="btn btn-sm btn-primary">{{ utility.description }}</a>
                                    </td>                                    
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'properties:utility_update' utility.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No utilities found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.description }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}