Property_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import ( 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('properties/', include('properties.urls', namespace='properties')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

leads/urls.py
from django.urls import path
from .views import (LeadListView, LeadDetailView, LeadCreateView, 
    LeadUpdateView, LeadDeleteView, AssignAgentView,
    CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    LeadDashboardView, CustomLoginView, MaintenanceRequestCreateView,
    MaintenanceRequestListView, MaintenanceRequestUpdateView,
    category_qr_code_detail, lead_category_qr_code, MaintenanceRequestDisplayView,
)

app_name = "leads"
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),
    path('dashboard/', LeadDashboardView.as_view(), name='lead-dashboard'),
    path('maintenance-request/create/', MaintenanceRequestCreateView.as_view(), name='maintenance-request-create'),
    path('maintenance_request/list/', MaintenanceRequestListView.as_view(), name='maintenance_request_list'),
    path('maintenance_request/update/<int:pk>/', MaintenanceRequestUpdateView.as_view(), name='maintenance_request_update'),
    path('maintenance_request/display/', MaintenanceRequestDisplayView.as_view(), name='maintenance_request_display'),
    path('category_qr_code_detail/<int:pk>/', category_qr_code_detail, name='category_qr_code_detail'),
    path('lead/<int:lead_id>/qr-code/', lead_category_qr_code, name='lead-category-qr-code'),
]

properties/urls.py
from django.urls import path
from .views import (
    PropertyListView, PropertyCreateView, ApartmentCreateView, 
    PropertyDetailView, UtilityCreateView, UtilityUpdateView, UtilityListView,
    UtilityDetailView, BillCreateView, BillDetailView, ApartmentDetailView,
    ApartmentUpdateView,
)

app_name = "properties"

urlpatterns = [
    path('', PropertyListView.as_view(), name='property-list'),
    path('create/', PropertyCreateView.as_view(), name='property-create'),
    path('<int:pk>/', PropertyDetailView.as_view(), name='property-detail'),
    path('create-apartment/', ApartmentCreateView.as_view(), name='apartment-create'),
    path('utilities/detail/<int:property_id>/<int:utility_pk>/', UtilityDetailView.as_view(), name='utility_detail_list'),
    path('utility/list/<int:property_id>/', UtilityListView.as_view(), name='utility-list'),
    path('utilities/create/', UtilityCreateView.as_view(), name='utility_create'),
    path('utilities/<int:pk>/update/', UtilityUpdateView.as_view(), name='utility_update'),
    path('utilities/<int:utility_id>/bills/create/', BillCreateView.as_view(), name='bill_create'),
    path('bills/<int:pk>/', BillDetailView.as_view(), name='bill_detail'),
    path('apartment/<int:pk>/', ApartmentDetailView.as_view(), name='apartment-detail'),
    path('apartment/<int:pk>/update/', ApartmentUpdateView.as_view(), name='apartment-update'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Property Management</title>
    <link href="{% static 'CSS/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100 min-h-screen">
    <div class="min-h-screen flex flex-col">
        {% include 'navbar.html' %}
        <div class="flex-1 container mx-auto px-4 py-8 sm:py-12">
          {% block content %}
          {% endblock content %}
        </div>
    </div>
    {% include 'chatbot/chatbot_widget.html' %}
</body>

<footer class="bg-gray-900 text-white py-4">
    <div class="container mx-auto px-4">
      <p class="text-center text-sm sm:text-base">&copy; {% now "Y" %} My Company. All rights reserved.</p>
    </div>
  </footer>
</html>

templates/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Hero Section -->
  <section class="bg-blue-500 text-white py-16" style="background-color: #415A77;">
    <div class="container mx-auto px-4 flex flex-col md:flex-row items-center">
      <div class="md:w-1/2">
        <h1 class="text-4xl sm:text-5xl font-bold mb-4">Effortlessly Manage Your Rental Properties with Rentify</h1>
        <p class="text-white text-opacity-75 mb-8">Rentify simplifies property management with a centralized platform, AI-assisted record-keeping, and an assistive chatbot for support. Our tenant dashboard enables rent tracking and maintenance requests, enhancing rental experiences for landlords and tenants alike.</p>
        <a href="{% url 'signup' %}" class="bg-white text-black py-2 px-4 rounded hover:bg-gray-300 hover:text-white inline-block">Get Started</a>
      </div>
      <div class="md:w-1/2">
        <img src="{% static 'images/rental.jpg' %}" alt="Placeholder Image" class="rounded shadow-lg ml-20">
      </div>
    </div>
  </section>

  <!-- Features Section -->
  <section class="bg-gray-100 py-16">
    <div class="container mx-auto px-4">
      <h2 class="text-3xl font-bold mb-8">Features</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div class="bg-white rounded-lg shadow-lg p-8">
          <h3 class="text-2xl font-bold mb-4">Centralized Property & Tenant Information</h3>
          <p class="mb-4">Rentify offers a comprehensive platform for landlords to consolidate all their property and tenant information in one user-friendly interface. This centralization facilitates seamless data management and access, streamlining property-related tasks and contributing to a more efficient property management experience.</p>
        </div>
        <div class="bg-white rounded-lg shadow-lg p-8">
          <h3 class="text-2xl font-bold mb-4">AI OCR for Record-Keeping & AI Chatbot Support</h3>
          <p class="mb-4">Rentify's AI OCR feature makes it easy for landlords to keep track of bills and expenses, ensuring a streamlined financial management process. Our AI-powered chatbot is also available to provide assistance and answer any queries related to the operation of the system, making it easier for landlords and tenants to manage their properties effectively.</p>
      </div>
      <div class="bg-white rounded-lg shadow-lg p-8">
          <h3 class="text-2xl font-bold mb-4">Tenant Dashboard for Rent Status and Maintenance Requests</h3>
          <p class="mb-4">Rentify's property management platform offers a comprehensive tenant dashboard, allowing tenants to monitor their rent status and submit maintenance requests for their apartments. This feature empowers tenants to stay informed and ensures that their concerns are addressed promptly, contributing to a better overall rental experience.</p>
      </div>
      </div>
    </div>
  </section>


{% endblock content %}

templates/navbar.html
{% load static %}

<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a href="{% url 'leads:lead-list' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <div class="flex justify-center items-center">
        <div class="w-10 h-10 mr-2">
          <img src="{% static 'images/property.png' %}" alt="Rentify logo" class="w-full h-full object-contain">
        </div>
        <div class="text-2xl">Rentify</div>
      </div>
      
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class=mr-5 hover:text-gray-900>Sign up</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
      {% if request.user.is_organisor %}
      <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
      <a href="{% url 'properties:property-list' %}" class="mr-5 hover:text-gray-900">Properties</a>
      <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Tenants</a>
      <a href="{% url 'leads:maintenance_request_display' %}" class="mr-5 hover:text-gray-900">Maintenace Requests</a>
      {% elif request.user.is_agent %}
      <a href="#" class="mr-5 hover:text-gray-900">Tenants</a>
      <a href="#" class="mr-5 hover:text-gray-900">Maintenace Requests</a>
      {% elif request.user.is_lead %}
      <a href="{% url 'leads:lead-dashboard' %}" class="mr-5 hover:text-gray-900">Dashboard</a>
      {% endif %}
      <p class="mr-5">You are logged in as: {{ request.user.username }}</p>
      <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% else %}
    <a href="{% url 'leads:login' %}" class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'JS/main.js' %}"></script>